-- INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('Alpha-3(bibliographic)','Alpha-3(terminologic)','Alpha-2','EnglishName','FrenchName');
-- Source: Adapted from http://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt
DELETE FROM [ISO639_2]

INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('aar',NULL,'aa','Afar','afar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('abk',NULL,'ab','Abkhazian','abkhaze');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ace',NULL,NULL,'Achinese','aceh');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ach',NULL,NULL,'Acoli','acoli');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ada',NULL,NULL,'Adangme','adangme');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ady',NULL,NULL,'Adyghe; Adygei','adyghé');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('afa',NULL,NULL,'Afro-Asiatic languages','afro-asiatiques, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('afh',NULL,NULL,'Afrihili','afrihili');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('afr',NULL,'af','Afrikaans','afrikaans');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ain',NULL,NULL,'Ainu','aïnou');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('aka',NULL,'ak','Akan','akan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('akk',NULL,NULL,'Akkadian','akkadien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('alb','sqi','sq','Albanian','albanais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ale',NULL,NULL,'Aleut','aléoute');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('alg',NULL,NULL,'Algonquian languages','algonquines, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('alt',NULL,NULL,'Southern Altai','altai du Sud');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('amh',NULL,'am','Amharic','amharique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ang',NULL,NULL,'English, Old (ca.450-1100)','anglo-saxon (ca.450-1100)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('anp',NULL,NULL,'Angika','angika');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('apa',NULL,NULL,'Apache languages','apaches, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ara',NULL,'ar','Arabic','arabe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('arc',NULL,NULL,'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)','araméen d''empire (700-300 BCE)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('arg',NULL,'an','Aragonese','aragonais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('arm','hye','hy','Armenian','arménien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('arn',NULL,NULL,'Mapudungun; Mapuche','mapudungun; mapuche; mapuce');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('arp',NULL,NULL,'Arapaho','arapaho');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('art',NULL,NULL,'Artificial languages','artificielles, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('arw',NULL,NULL,'Arawak','arawak');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('asm',NULL,'as','Assamese','assamais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ast',NULL,NULL,'Asturian; Bable; Leonese; Asturleonese','asturien; bable; léonais; asturoléonais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ath',NULL,NULL,'Athapascan languages','athapascanes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('aus',NULL,NULL,'Australian languages','australiennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ava',NULL,'av','Avaric','avar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ave',NULL,'ae','Avestan','avestique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('awa',NULL,NULL,'Awadhi','awadhi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('aym',NULL,'ay','Aymara','aymara');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('aze',NULL,'az','Azerbaijani','azéri');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bad',NULL,NULL,'Banda languages','banda, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bai',NULL,NULL,'Bamileke languages','bamiléké, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bak',NULL,'ba','Bashkir','bachkir');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bal',NULL,NULL,'Baluchi','baloutchi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bam',NULL,'bm','Bambara','bambara');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ban',NULL,NULL,'Balinese','balinais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('baq','eus','eu','Basque','basque');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bas',NULL,NULL,'Basa','basa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bat',NULL,NULL,'Baltic languages','baltes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bej',NULL,NULL,'Beja; Bedawiyet','bedja');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bel',NULL,'be','Belarusian','biélorusse');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bem',NULL,NULL,'Bemba','bemba');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ben',NULL,'bn','Bengali','bengali');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ber',NULL,NULL,'Berber languages','berbères, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bho',NULL,NULL,'Bhojpuri','bhojpuri');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bih',NULL,'bh','Bihari languages','langues biharis');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bik',NULL,NULL,'Bikol','bikol');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bin',NULL,NULL,'Bini; Edo','bini; edo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bis',NULL,'bi','Bislama','bichlamar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bla',NULL,NULL,'Siksika','blackfoot');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bnt',NULL,NULL,'Bantu (Other)','bantoues, autres langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bos',NULL,'bs','Bosnian','bosniaque');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bra',NULL,NULL,'Braj','braj');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bre',NULL,'br','Breton','breton');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('btk',NULL,NULL,'Batak languages','batak, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bua',NULL,NULL,'Buriat','bouriate');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bug',NULL,NULL,'Buginese','bugi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bul',NULL,'bg','Bulgarian','bulgare');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('bur','mya','my','Burmese','birman');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('byn',NULL,NULL,'Blin; Bilin','blin; bilen');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cad',NULL,NULL,'Caddo','caddo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cai',NULL,NULL,'Central American Indian languages','amérindiennes de L''Amérique centrale, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('car',NULL,NULL,'Galibi Carib','karib; galibi; carib');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cat',NULL,'ca','Catalan; Valencian','catalan; valencien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cau',NULL,NULL,'Caucasian languages','caucasiennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ceb',NULL,NULL,'Cebuano','cebuano');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cel',NULL,NULL,'Celtic languages','celtiques, langues; celtes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cha',NULL,'ch','Chamorro','chamorro');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chb',NULL,NULL,'Chibcha','chibcha');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('che',NULL,'ce','Chechen','tchétchène');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chg',NULL,NULL,'Chagatai','djaghataï');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chi','zho','zh','Chinese','chinois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chk',NULL,NULL,'Chuukese','chuuk');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chm',NULL,NULL,'Mari','mari');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chn',NULL,NULL,'Chinook jargon','chinook, jargon');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cho',NULL,NULL,'Choctaw','choctaw');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chp',NULL,NULL,'Chipewyan; Dene Suline','chipewyan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chr',NULL,NULL,'Cherokee','cherokee');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chu',NULL,'cu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','slavon d''église; vieux slave; slavon liturgique; vieux bulgare');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chv',NULL,'cv','Chuvash','tchouvache');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('chy',NULL,NULL,'Cheyenne','cheyenne');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cmc',NULL,NULL,'Chamic languages','chames, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cop',NULL,NULL,'Coptic','copte');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cor',NULL,'kw','Cornish','cornique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cos',NULL,'co','Corsican','corse');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cpe',NULL,NULL,'Creoles and pidgins, English based','créoles et pidgins basés sur l''anglais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cpf',NULL,NULL,'Creoles and pidgins, French-based ','créoles et pidgins basés sur le français');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cpp',NULL,NULL,'Creoles and pidgins, Portuguese-based ','créoles et pidgins basés sur le portugais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cre',NULL,'cr','Cree','cree');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('crh',NULL,NULL,'Crimean Tatar; Crimean Turkish','tatar de Crimé');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('crp',NULL,NULL,'Creoles and pidgins ','créoles et pidgins');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('csb',NULL,NULL,'Kashubian','kachoube');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cus',NULL,NULL,'Cushitic languages','couchitiques, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('cze','ces','cs','Czech','tchèque');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dak',NULL,NULL,'Dakota','dakota');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dan',NULL,'da','Danish','danois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dar',NULL,NULL,'Dargwa','dargwa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('day',NULL,NULL,'Land Dayak languages','dayak, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('del',NULL,NULL,'Delaware','delaware');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('den',NULL,NULL,'Slave (Athapascan)','esclave (athapascan)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dgr',NULL,NULL,'Dogrib','dogrib');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('din',NULL,NULL,'Dinka','dinka');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('div',NULL,'dv','Divehi; Dhivehi; Maldivian','maldivien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('doi',NULL,NULL,'Dogri','dogri');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dra',NULL,NULL,'Dravidian languages','dravidiennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dsb',NULL,NULL,'Lower Sorbian','bas-sorabe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dua',NULL,NULL,'Duala','douala');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dum',NULL,NULL,'Dutch, Middle (ca.1050-1350)','néerlandais moyen (ca. 1050-1350)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dut','nld','nl','Dutch; Flemish','néerlandais; flamand');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dyu',NULL,NULL,'Dyula','dioula');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('dzo',NULL,'dz','Dzongkha','dzongkha');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('efi',NULL,NULL,'Efik','efik');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('egy',NULL,NULL,'Egyptian (Ancient)','égyptien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('eka',NULL,NULL,'Ekajuk','ekajuk');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('elx',NULL,NULL,'Elamite','élamite');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('eng',NULL,'en','English','anglais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('enm',NULL,NULL,'English, Middle (1100-1500)','anglais moyen (1100-1500)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('epo',NULL,'eo','Esperanto','espéranto');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('est',NULL,'et','Estonian','estonien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ewe',NULL,'ee','Ewe','éwé');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ewo',NULL,NULL,'Ewondo','éwondo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fan',NULL,NULL,'Fang','fang');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fao',NULL,'fo','Faroese','féroïen');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fat',NULL,NULL,'Fanti','fanti');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fij',NULL,'fj','Fijian','fidjien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fil',NULL,NULL,'Filipino; Pilipino','filipino; pilipino');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fin',NULL,'fi','Finnish','finnois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fiu',NULL,NULL,'Finno-Ugrian languages','finno-ougriennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fon',NULL,NULL,'Fon','fon');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fre','fra','fr','French','français');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('frm',NULL,NULL,'French, Middle (ca.1400-1600)','français moyen (1400-1600)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fro',NULL,NULL,'French, Old (842-ca.1400)','français ancien (842-ca.1400)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('frr',NULL,NULL,'Northern Frisian','frison septentrional');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('frs',NULL,NULL,'Eastern Frisian','frison oriental');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fry',NULL,'fy','Western Frisian','frison occidental');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ful',NULL,'ff','Fulah','peul');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('fur',NULL,NULL,'Friulian','frioulan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gaa',NULL,NULL,'Ga','ga');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gay',NULL,NULL,'Gayo','gayo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gba',NULL,NULL,'Gbaya','gbaya');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gem',NULL,NULL,'Germanic languages','germaniques, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('geo','kat','ka','Georgian','géorgien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ger','deu','de','German','allemand');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gez',NULL,NULL,'Geez','guèze');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gil',NULL,NULL,'Gilbertese','kiribati');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gla',NULL,'gd','Gaelic; Scottish Gaelic','gaélique; gaélique écossais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gle',NULL,'ga','Irish','irlandais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('glg',NULL,'gl','Galician','galicien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('glv',NULL,'gv','Manx','manx; mannois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gmh',NULL,NULL,'German, Middle High (ca.1050-1500)','allemand, moyen haut (ca. 1050-1500)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('goh',NULL,NULL,'German, Old High (ca.750-1050)','allemand, vieux haut (ca. 750-1050)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gon',NULL,NULL,'Gondi','gond');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gor',NULL,NULL,'Gorontalo','gorontalo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('got',NULL,NULL,'Gothic','gothique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('grb',NULL,NULL,'Grebo','grebo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('grc',NULL,NULL,'Greek, Ancient (to 1453)','grec ancien (jusqu''à 1453)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gre','ell','el','Greek, Modern (1453-)','grec moderne (après 1453)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('grn',NULL,'gn','Guarani','guarani');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gsw',NULL,NULL,'Swiss German; Alemannic; Alsatian','suisse alémanique; alémanique; alsacien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('guj',NULL,'gu','Gujarati','goudjrati');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('gwi',NULL,NULL,'Gwich''in','gwich''in');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hai',NULL,NULL,'Haida','haida');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hat',NULL,'ht','Haitian; Haitian Creole','haïtien; créole haïtien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hau',NULL,'ha','Hausa','haoussa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('haw',NULL,NULL,'Hawaiian','hawaïen');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('heb',NULL,'he','Hebrew','hébreu');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('her',NULL,'hz','Herero','herero');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hil',NULL,NULL,'Hiligaynon','hiligaynon');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('him',NULL,NULL,'Himachali languages; Western Pahari languages','langues himachalis; langues paharis occidentales');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hin',NULL,'hi','Hindi','hindi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hit',NULL,NULL,'Hittite','hittite');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hmn',NULL,NULL,'Hmong; Mong','hmong');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hmo',NULL,'ho','Hiri Motu','hiri motu');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hrv',NULL,'hr','Croatian','croate');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hsb',NULL,NULL,'Upper Sorbian','haut-sorabe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hun',NULL,'hu','Hungarian','hongrois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('hup',NULL,NULL,'Hupa','hupa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('iba',NULL,NULL,'Iban','iban');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ibo',NULL,'ig','Igbo','igbo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ice','isl','is','Icelandic','islandais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ido',NULL,'io','Ido','ido');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('iii',NULL,'ii','Sichuan Yi; Nuosu','yi de Sichuan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ijo',NULL,NULL,'Ijo languages','ijo, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('iku',NULL,'iu','Inuktitut','inuktitut');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ile',NULL,'ie','Interlingue; Occidental','interlingue');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ilo',NULL,NULL,'Iloko','ilocano');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ina',NULL,'ia','Interlingua (International Auxiliary Language Association)','interlingua (langue auxiliaire internationale)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('inc',NULL,NULL,'Indic languages','indo-aryennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ind',NULL,'id','Indonesian','indonésien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ine',NULL,NULL,'Indo-European languages','indo-européennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('inh',NULL,NULL,'Ingush','ingouche');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ipk',NULL,'ik','Inupiaq','inupiaq');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ira',NULL,NULL,'Iranian languages','iraniennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('iro',NULL,NULL,'Iroquoian languages','iroquoises, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ita',NULL,'it','Italian','italien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('jav',NULL,'jv','Javanese','javanais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('jbo',NULL,NULL,'Lojban','lojban');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('jpn',NULL,'ja','Japanese','japonais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('jpr',NULL,NULL,'Judeo-Persian','judéo-persan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('jrb',NULL,NULL,'Judeo-Arabic','judéo-arabe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kaa',NULL,NULL,'Kara-Kalpak','karakalpak');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kab',NULL,NULL,'Kabyle','kabyle');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kac',NULL,NULL,'Kachin; Jingpho','kachin; jingpho');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kal',NULL,'kl','Kalaallisut; Greenlandic','groenlandais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kam',NULL,NULL,'Kamba','kamba');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kan',NULL,'kn','Kannada','kannada');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kar',NULL,NULL,'Karen languages','karen, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kas',NULL,'ks','Kashmiri','kashmiri');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kau',NULL,'kr','Kanuri','kanouri');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kaw',NULL,NULL,'Kawi','kawi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kaz',NULL,'kk','Kazakh','kazakh');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kbd',NULL,NULL,'Kabardian','kabardien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kha',NULL,NULL,'Khasi','khasi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('khi',NULL,NULL,'Khoisan languages','khoïsan, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('khm',NULL,'km','Central Khmer','khmer central');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kho',NULL,NULL,'Khotanese; Sakan','khotanais; sakan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kik',NULL,'ki','Kikuyu; Gikuyu','kikuyu');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kin',NULL,'rw','Kinyarwanda','rwanda');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kir',NULL,'ky','Kirghiz; Kyrgyz','kirghiz');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kmb',NULL,NULL,'Kimbundu','kimbundu');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kok',NULL,NULL,'Konkani','konkani');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kom',NULL,'kv','Komi','kom');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kon',NULL,'kg','Kongo','kongo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kor',NULL,'ko','Korean','coréen');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kos',NULL,NULL,'Kosraean','kosrae');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kpe',NULL,NULL,'Kpelle','kpellé');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('krc',NULL,NULL,'Karachay-Balkar','karatchai balkar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('krl',NULL,NULL,'Karelian','carélien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kro',NULL,NULL,'Kru languages','krou, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kru',NULL,NULL,'Kurukh','kurukh');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kua',NULL,'kj','Kuanyama; Kwanyama','kuanyama; kwanyama');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kum',NULL,NULL,'Kumyk','koumyk');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kur',NULL,'ku','Kurdish','kurde');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('kut',NULL,NULL,'Kutenai','kutenai');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lad',NULL,NULL,'Ladino','judéo-espagnol');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lah',NULL,NULL,'Lahnda','lahnda');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lam',NULL,NULL,'Lamba','lamba');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lao',NULL,'lo','Lao','lao');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lat',NULL,'la','Latin','latin');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lav',NULL,'lv','Latvian','letton');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lez',NULL,NULL,'Lezghian','lezghien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lim',NULL,'li','Limburgan; Limburger; Limburgish','limbourgeois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lin',NULL,'ln','Lingala','lingala');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lit',NULL,'lt','Lithuanian','lituanien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lol',NULL,NULL,'Mongo','mongo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('loz',NULL,NULL,'Lozi','lozi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ltz',NULL,'lb','Luxembourgish; Letzeburgesch','luxembourgeois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lua',NULL,NULL,'Luba-Lulua','luba-lulua');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lub',NULL,'lu','Luba-Katanga','luba-katanga');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lug',NULL,'lg','Ganda','ganda');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lui',NULL,NULL,'Luiseno','luiseno');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lun',NULL,NULL,'Lunda','lunda');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('luo',NULL,NULL,'Luo (Kenya and Tanzania)','luo (Kenya et Tanzanie)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('lus',NULL,NULL,'Lushai','lushai');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mac','mkd','mk','Macedonian','macédonien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mad',NULL,NULL,'Madurese','madourais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mag',NULL,NULL,'Magahi','magahi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mah',NULL,'mh','Marshallese','marshall');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mai',NULL,NULL,'Maithili','maithili');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mak',NULL,NULL,'Makasar','makassar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mal',NULL,'ml','Malayalam','malayalam');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('man',NULL,NULL,'Mandingo','mandingue');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mao','mri','mi','Maori','maori');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('map',NULL,NULL,'Austronesian languages','austronésiennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mar',NULL,'mr','Marathi','marathe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mas',NULL,NULL,'Masai','massaï');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('may','msa','ms','Malay','malais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mdf',NULL,NULL,'Moksha','moksa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mdr',NULL,NULL,'Mandar','mandar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('men',NULL,NULL,'Mende','mendé');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mga',NULL,NULL,'Irish, Middle (900-1200)','irlandais moyen (900-1200)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mic',NULL,NULL,'Mi''kmaq; Micmac','mi''kmaq; micmac');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('min',NULL,NULL,'Minangkabau','minangkabau');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mis',NULL,NULL,'Uncoded languages','langues non codées');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mkh',NULL,NULL,'Mon-Khmer languages','môn-khmer, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mlg',NULL,'mg','Malagasy','malgache');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mlt',NULL,'mt','Maltese','maltais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mnc',NULL,NULL,'Manchu','mandchou');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mni',NULL,NULL,'Manipuri','manipuri');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mno',NULL,NULL,'Manobo languages','manobo, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('moh',NULL,NULL,'Mohawk','mohawk');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mon',NULL,'mn','Mongolian','mongol');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mos',NULL,NULL,'Mossi','moré');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mul',NULL,NULL,'Multiple languages','multilingue');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mun',NULL,NULL,'Munda languages','mounda, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mus',NULL,NULL,'Creek','muskogee');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mwl',NULL,NULL,'Mirandese','mirandais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('mwr',NULL,NULL,'Marwari','marvari');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('myn',NULL,NULL,'Mayan languages','maya, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('myv',NULL,NULL,'Erzya','erza');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nah',NULL,NULL,'Nahuatl languages','nahuatl, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nai',NULL,NULL,'North American Indian languages','nord-amérindiennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nap',NULL,NULL,'Neapolitan','napolitain');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nau',NULL,'na','Nauru','nauruan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nav',NULL,'nv','Navajo; Navaho','navaho');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nbl',NULL,'nr','Ndebele, South; South Ndebele','ndébélé du Sud');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nde',NULL,'nd','Ndebele, North; North Ndebele','ndébélé du Nord');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ndo',NULL,'ng','Ndonga','ndonga');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nds',NULL,NULL,'Low German; Low Saxon; German, Low; Saxon, Low','bas allemand; bas saxon; allemand, bas; saxon, bas');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nep',NULL,'ne','Nepali','népalais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('new',NULL,NULL,'Nepal Bhasa; Newari','nepal bhasa; newari');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nia',NULL,NULL,'Nias','nias');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nic',NULL,NULL,'Niger-Kordofanian languages','nigéro-kordofaniennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('niu',NULL,NULL,'Niuean','niué');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nno',NULL,'nn','Norwegian Nynorsk; Nynorsk, Norwegian','norvégien nynorsk; nynorsk, norvégien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nob',NULL,'nb','Bokmål, Norwegian; Norwegian Bokmål','norvégien bokmål');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nog',NULL,NULL,'Nogai','nogaï; nogay');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('non',NULL,NULL,'Norse, Old','norrois, vieux');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nor',NULL,'no','Norwegian','norvégien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nqo',NULL,NULL,'N''Ko','n''ko');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nso',NULL,NULL,'Pedi; Sepedi; Northern Sotho','pedi; sepedi; sotho du Nord');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nub',NULL,NULL,'Nubian languages','nubiennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nwc',NULL,NULL,'Classical Newari; Old Newari; Classical Nepal Bhasa','newari classique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nya',NULL,'ny','Chichewa; Chewa; Nyanja','chichewa; chewa; nyanja');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nym',NULL,NULL,'Nyamwezi','nyamwezi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nyn',NULL,NULL,'Nyankole','nyankolé');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nyo',NULL,NULL,'Nyoro','nyoro');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('nzi',NULL,NULL,'Nzima','nzema');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('oci',NULL,'oc','Occitan (post 1500); Provençal','occitan (après 1500); provençal');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('oji',NULL,'oj','Ojibwa','ojibwa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ori',NULL,'or','Oriya','oriya');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('orm',NULL,'om','Oromo','galla');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('osa',NULL,NULL,'Osage','osage');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('oss',NULL,'os','Ossetian; Ossetic','ossète');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ota',NULL,NULL,'Turkish, Ottoman (1500-1928)','turc ottoman (1500-1928)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('oto',NULL,NULL,'Otomian languages','otomi, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('paa',NULL,NULL,'Papuan languages','papoues, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pag',NULL,NULL,'Pangasinan','pangasinan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pal',NULL,NULL,'Pahlavi','pahlavi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pam',NULL,NULL,'Pampanga; Kapampangan','pampangan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pan',NULL,'pa','Panjabi; Punjabi','pendjabi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pap',NULL,NULL,'Papiamento','papiamento');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pau',NULL,NULL,'Palauan','palau');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('peo',NULL,NULL,'Persian, Old (ca.600-400 B.C.)','perse, vieux (ca. 600-400 av. J.-C.)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('per','fas','fa','Persian','persan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('phi',NULL,NULL,'Philippine languages','philippines, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('phn',NULL,NULL,'Phoenician','phénicien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pli',NULL,'pi','Pali','pali');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pol',NULL,'pl','Polish','polonais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pon',NULL,NULL,'Pohnpeian','pohnpei');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('por',NULL,'pt','Portuguese','portugais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pra',NULL,NULL,'Prakrit languages','prâkrit, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pro',NULL,NULL,'Provençal, Old (to 1500)','provençal ancien (jusqu''à 1500)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('pus',NULL,'ps','Pushto; Pashto','pachto');

-- qaa-qtz
DECLARE @Alpha3B nchar(1)
DECLARE @Alpha3C nchar(1)
SET @Alpha3B = 'a'
WHILE ASCII(@Alpha3B) <= ASCII('t')
BEGIN
    SET @Alpha3C = 'a'
    WHILE ASCII(@Alpha3C) <= ASCII('z')
    BEGIN
        INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames)
            VALUES ('q' + @Alpha3B + @Alpha3C,NULL,NULL,'Reserved for local use','réservée à l''usage local')
        SET @Alpha3C = CHAR(ASCII(@Alpha3C) + 1)
    END
    SET @Alpha3B = CHAR(ASCII(@Alpha3B) + 1)
END

INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('que',NULL,'qu','Quechua','quechua');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('raj',NULL,NULL,'Rajasthani','rajasthani');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('rap',NULL,NULL,'Rapanui','rapanui');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('rar',NULL,NULL,'Rarotongan; Cook Islands Maori','rarotonga; maori des îles Cook');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('roa',NULL,NULL,'Romance languages','romanes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('roh',NULL,'rm','Romansh','romanche');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('rom',NULL,NULL,'Romany','tsigane');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('rum','ron','ro','Romanian; Moldavian; Moldovan','roumain; moldave');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('run',NULL,'rn','Rundi','rundi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('rup',NULL,NULL,'Aromanian; Arumanian; Macedo-Romanian','aroumain; macédo-roumain');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('rus',NULL,'ru','Russian','russe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sad',NULL,NULL,'Sandawe','sandawe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sag',NULL,'sg','Sango','sango');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sah',NULL,NULL,'Yakut','iakoute');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sai',NULL,NULL,'South American Indian (Other)','indiennes d''Amérique du Sud, autres langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sal',NULL,NULL,'Salishan languages','salishennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sam',NULL,NULL,'Samaritan Aramaic','samaritain');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('san',NULL,'sa','Sanskrit','sanskrit');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sas',NULL,NULL,'Sasak','sasak');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sat',NULL,NULL,'Santali','santal');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('scn',NULL,NULL,'Sicilian','sicilien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sco',NULL,NULL,'Scots','écossais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sel',NULL,NULL,'Selkup','selkoupe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sem',NULL,NULL,'Semitic languages','sémitiques, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sga',NULL,NULL,'Irish, Old (to 900)','irlandais ancien (jusqu''à 900)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sgn',NULL,NULL,'Sign Languages','langues des signes');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('shn',NULL,NULL,'Shan','chan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sid',NULL,NULL,'Sidamo','sidamo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sin',NULL,'si','Sinhala; Sinhalese','singhalais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sio',NULL,NULL,'Siouan languages','sioux, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sit',NULL,NULL,'Sino-Tibetan languages','sino-tibétaines, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sla',NULL,NULL,'Slavic languages','slaves, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('slo','slk','sk','Slovak','slovaque');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('slv',NULL,'sl','Slovenian','slovène');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sma',NULL,NULL,'Southern Sami','sami du Sud');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sme',NULL,'se','Northern Sami','sami du Nord');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('smi',NULL,NULL,'Sami languages','sames, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('smj',NULL,NULL,'Lule Sami','sami de Lule');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('smn',NULL,NULL,'Inari Sami','sami d''Inari');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('smo',NULL,'sm','Samoan','samoan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sms',NULL,NULL,'Skolt Sami','sami skolt');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sna',NULL,'sn','Shona','shona');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('snd',NULL,'sd','Sindhi','sindhi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('snk',NULL,NULL,'Soninke','soninké');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sog',NULL,NULL,'Sogdian','sogdien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('som',NULL,'so','Somali','somali');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('son',NULL,NULL,'Songhai languages','songhai, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sot',NULL,'st','Sotho, Southern','sotho du Sud');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('spa',NULL,'es','Spanish; Castilian','espagnol; castillan');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('srd',NULL,'sc','Sardinian','sarde');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('srn',NULL,NULL,'Sranan Tongo','sranan tongo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('srp',NULL,'sr','Serbian','serbe');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('srr',NULL,NULL,'Serer','sérère');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ssa',NULL,NULL,'Nilo-Saharan languages','nilo-sahariennes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ssw',NULL,'ss','Swati','swati');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('suk',NULL,NULL,'Sukuma','sukuma');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sun',NULL,'su','Sundanese','soundanais');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sus',NULL,NULL,'Susu','soussou');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('sux',NULL,NULL,'Sumerian','sumérien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('swa',NULL,'sw','Swahili','swahili');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('swe',NULL,'sv','Swedish','suédois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('syc',NULL,NULL,'Classical Syriac','syriaque classique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('syr',NULL,NULL,'Syriac','syriaque');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tah',NULL,'ty','Tahitian','tahitien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tai',NULL,NULL,'Tai languages','tai, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tam',NULL,'ta','Tamil','tamoul');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tat',NULL,'tt','Tatar','tatar');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tel',NULL,'te','Telugu','télougou');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tem',NULL,NULL,'Timne','temne');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ter',NULL,NULL,'Tereno','tereno');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tet',NULL,NULL,'Tetum','tetum');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tgk',NULL,'tg','Tajik','tadjik');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tgl',NULL,'tl','Tagalog','tagalog');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tha',NULL,'th','Thai','thaï');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tib','bod','bo','Tibetan','tibétain');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tig',NULL,NULL,'Tigre','tigré');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tir',NULL,'ti','Tigrinya','tigrigna');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tiv',NULL,NULL,'Tiv','tiv');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tkl',NULL,NULL,'Tokelau','tokelau');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tlh',NULL,NULL,'Klingon; tlhIngan-Hol','klingon');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tli',NULL,NULL,'Tlingit','tlingit');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tmh',NULL,NULL,'Tamashek','tamacheq');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tog',NULL,NULL,'Tonga (Nyasa)','tonga (Nyasa)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ton',NULL,'to','Tonga (Tonga Islands)','tongan (Îles Tonga)');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tpi',NULL,NULL,'Tok Pisin','tok pisin');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tsi',NULL,NULL,'Tsimshian','tsimshian');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tsn',NULL,'tn','Tswana','tswana');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tso',NULL,'ts','Tsonga','tsonga');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tuk',NULL,'tk','Turkmen','turkmène');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tum',NULL,NULL,'Tumbuka','tumbuka');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tup',NULL,NULL,'Tupi languages','tupi, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tur',NULL,'tr','Turkish','turc');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tut',NULL,NULL,'Altaic languages','altaïques, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tvl',NULL,NULL,'Tuvalu','tuvalu');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('twi',NULL,'tw','Twi','twi');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('tyv',NULL,NULL,'Tuvinian','touva');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('udm',NULL,NULL,'Udmurt','oudmourte');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('uga',NULL,NULL,'Ugaritic','ougaritique');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('uig',NULL,'ug','Uighur; Uyghur','ouïgour');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ukr',NULL,'uk','Ukrainian','ukrainien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('umb',NULL,NULL,'Umbundu','umbundu');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('und',NULL,NULL,'Undetermined','indéterminée');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('urd',NULL,'ur','Urdu','ourdou');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('uzb',NULL,'uz','Uzbek','ouszbek');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('vai',NULL,NULL,'Vai','vaï');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ven',NULL,'ve','Venda','venda');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('vie',NULL,'vi','Vietnamese','vietnamien');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('vol',NULL,'vo','Volapük','volapük');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('vot',NULL,NULL,'Votic','vote');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('wak',NULL,NULL,'Wakashan languages','wakashanes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('wal',NULL,NULL,'Walamo','walamo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('war',NULL,NULL,'Waray','waray');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('was',NULL,NULL,'Washo','washo');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('wel','cym','cy','Welsh','gallois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('wen',NULL,NULL,'Sorbian languages','sorabes, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('wln',NULL,'wa','Walloon','wallon');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('wol',NULL,'wo','Wolof','wolof');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('xal',NULL,NULL,'Kalmyk; Oirat','kalmouk; oïrat');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('xho',NULL,'xh','Xhosa','xhosa');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('yao',NULL,NULL,'Yao','yao');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('yap',NULL,NULL,'Yapese','yapois');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('yid',NULL,'yi','Yiddish','yiddish');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('yor',NULL,'yo','Yoruba','yoruba');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('ypk',NULL,NULL,'Yupik languages','yupik, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zap',NULL,NULL,'Zapotec','zapotèque');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zbl',NULL,NULL,'Blissymbols; Blissymbolics; Bliss','symboles Bliss; Bliss');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zen',NULL,NULL,'Zenaga','zenaga');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zha',NULL,'za','Zhuang; Chuang','zhuang; chuang');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('znd',NULL,NULL,'Zande languages','zandé, langues');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zul',NULL,'zu','Zulu','zoulou');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zun',NULL,NULL,'Zuni','zuni');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zxx',NULL,NULL,'No linguistic content; Not applicable','pas de contenu linguistique; non applicable');
INSERT INTO [ISO639_2](Alpha3B,Alpha3T,Alpha2,EnglishNames,FrenchNames) VALUES ('zza',NULL,NULL,'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki','zaza; dimili; dimli; kirdki; kirmanjki; zazaki');