INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Abbey','ABBEY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Acres','ACRES',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Allée','ALLÉE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Alley','ALLEY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Autoroute','AUT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Avenue','AVE','en-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Avenue','AV','fr-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Bay','BAY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Beach','BEACH',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Bend','BEND',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Boulevard','BLVD','en-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Boulevard','BOUL','fr-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('By-pass','BYPASS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Byway','BYWAY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Campus','CAMPUS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Cape','CAPE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Carré','CAR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Carrefour','CARREF',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Centre','CTR','en-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Centre','C','fr-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Cercle','CERCLE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Chase','CHASE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Chemin','CH',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Circle','CIR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Circuit','CIRCT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Close','CLOSE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Common','COMMON',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Concession','CONC',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Corners','CRNRS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Côte','CÔTE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Cour','COUR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Cours','COURS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Court','CRT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Cove','COVE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Crescent','CRES',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Croissant','CROIS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Crossing','CROSS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Cul-de-sac','CDS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Dale','DALE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Dell','DELL',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Diversion','DIVERS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Downs','DOWNS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Drive','DR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Échangeur','ÉCH',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('End','END',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Esplanade','ESPL',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Estates','ESTATE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Expressway','EXPY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Extension','EXTEN',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Farm','FARM',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Field','FIELD',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Forest','FOREST',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Freeway','FWY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Front','FRONT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Gardens','GDNS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Gate','GATE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Glade','GLADE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Glen','GLEN',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Green','GREEN',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Grounds','GRNDS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Grove','GROVE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Harbour','HARBR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Heath','HEATH',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Heights','HTS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Highlands','HGHLDS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Highway','HWY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Hill','HILL',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Hollow','HOLLOW',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Île','ÎLE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Impasse','IMP',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Inlet','INLET',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Island','ISLAND',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Key','KEY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Knoll','KNOLL',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Landing','LANDNG',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Lane','LANE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Limits','LMTS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Line','LINE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Link','LINK',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Lookout','LKOUT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Loop','LOOP',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Mall','MALL',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Manor','MANOR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Maze','MAZE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Meadow','MEADOW',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Mews','MEWS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Montée','MONTÉE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Moor','MOOR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Mount','MOUNT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Mountain','MTN',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Orchard','ORCH',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Parade','PARADE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Parc','PARC',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Park','PK',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Parkway','PKY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Passage','PASS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Path','PATH',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Pathway','PTWAY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Pines','PINES',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Place','PL','en-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Place','PLACE','fr-CA');
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Plateau','PLAT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Plaza','PLAZA',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Point','PT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Pointe','POINTE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Port','PORT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Private','PVT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Promenade','PROM',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Quai','QUAI',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Quay','QUAY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Ramp','RAMP',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Rang','RANG',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Range','RG',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Ridge','RIDGE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Rise','RISE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Road','RD',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Rond-point','RDPT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Route','RTE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Row','ROW',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Rue','RUE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Ruelle','RLE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Run','RUN',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Sentier','SENT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Square','SQ',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Street','ST',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Subdivision','SUBDIV',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Terrace','TERR',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Terrasse','TSSE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Thicket','THICK',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Towers','TOWERS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Townline','TLINE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Trail','TRAIL',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Turnabout','TRNABT',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Vale','VALE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Via','VIA',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('View','VIEW',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Village','VILLGE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Villas','VILLAS',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Vista','VISTA',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Voie','VOIE',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Walk','WALK',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Way','WAY',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Wharf','WHARF',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Wood','WOOD',NULL);
GO;
INSERT INTO StreetType(StreetType,Abbreviation,Language) VALUES ('Wynd','WYND',NULL);
